title: Malaria Dashboard Application
logo: /assets/img/pmi_logo.png
description: Welcome to the Malaria Dashboard Application website.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal