title: Application Malaria Dashboard
# logo: /assets/img/dashboard_logo.png
ownerlogo: /assets/img/pmi_logo.png
qr: /assets/img/dashboard_qrc.png
description: Bienvenu sur le site de l'application Malaria Dashboard.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal